### ISSUE TITLE
Docker / Jupyter error when opening notebook

### ISSUE THREAD

**Issue by CYHSM** [sinzlab/sensorium#107]
Hey everone, I have a problem after starting jupyter lab, it opens fine in the browser but then it throws unknown error when opening any notebook. The log says the following: 

> [I 10:03:22.618 LabApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
> [W 10:03:23.028 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
> [I 10:03:23.373 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.8/dist-packages/jupyterlab
> [I 10:03:23.373 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
> [I 10:03:23.381 LabApp] Serving notebooks from local directory: /notebooks
> [I 10:03:23.381 LabApp] Jupyter Notebook 6.1.5 is running at:
> [I 10:03:23.382 LabApp] http://1b853573bd1b:8888/
> [I 10:03:23.382 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
> [I 10:03:52.342 LabApp] 302 GET / (172.18.0.1) 1.55ms
> [I 10:03:54.485 LabApp] Build is up to date
> /[I 10:03:59.754 LabApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
> [W 10:03:59.764 LabApp] Notebook dataset_tutorial/1_inspect_data.ipynb is not trusted
> [E 10:04:01.258 LabApp] Uncaught exception POST /api/sessions?1657361041181 (172.18.0.1)
>     HTTPServerRequest(protocol='http', host='localhost:10101', method='POST', uri='/api/sessions?1657361041181', version='HTTP/1.1', remote_ip='172.18.0.1')
>     Traceback (most recent call last):
>       File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1704, in _execute
>         result = await result
>       File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 769, in run
>         yielded = self.gen.throw(*exc_info)  # type: ignore
>       File "/usr/local/lib/python3.8/dist-packages/notebook/services/sessions/handlers.py", line 69, in post
>         model = yield maybe_future(
>       File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 762, in run
>         value = future.result()
>       File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 769, in run
>         yielded = self.gen.throw(*exc_info)  # type: ignore
>       File "/usr/local/lib/python3.8/dist-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
>         kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
>       File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 762, in run
>         value = future.result()
>       File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 769, in run
>         yielded = self.gen.throw(*exc_info)  # type: ignore
>       File "/usr/local/lib/python3.8/dist-packages/notebook/services/sessions/sessionmanager.py", line 100, in start_kernel_for_session
>         kernel_id = yield maybe_future(
>       File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 762, in run
>         value = future.result()
>       File "/usr/local/lib/python3.8/dist-packages/notebook/services/kernels/kernelmanager.py", line 176, in start_kernel
>         kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
>       File "/usr/local/lib/python3.8/dist-packages/jupyter_client/multikernelmanager.py", line 185, in start_kernel
>         km.start_kernel(**kwargs)
>       File "/usr/local/lib/python3.8/dist-packages/jupyter_client/manager.py", line 309, in start_kernel
>         kernel_cmd, kw = self.pre_start_kernel(**kw)
>       File "/usr/local/lib/python3.8/dist-packages/jupyter_client/manager.py", line 256, in pre_start_kernel
>         self.write_connection_file()
>       File "/usr/local/lib/python3.8/dist-packages/jupyter_client/connect.py", line 468, in write_connection_file
>         self.connection_file, cfg = write_connection_file(self.connection_file,
>       File "/usr/local/lib/python3.8/dist-packages/jupyter_client/connect.py", line 138, in write_connection_file
>         with secure_write(fname) as f:
>       File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
>         return next(self.gen)
>       File "/usr/local/lib/python3.8/dist-packages/jupyter_core/paths.py", line 445, in secure_write
>         raise RuntimeError("Permissions assignment failed for secure file: '{file}'."
>     RuntimeError: Permissions assignment failed for secure file: '/root/.local/share/jupyter/runtime/kernel-5aaf7e09-2bc8-467b-a48f-3568c308e0e4.json'. Got '0o677' instead of '0o0600'.

I tried a lot of different thing over the last two days to fix this but I cant seem to fix it. I reinstalled docker and docker compose, ran it with and without sudo but the error stays the same. Output of jupyter --paths is the following:

> config:
>     /root/.jupyter
>     /usr/etc/jupyter
>     /usr/local/etc/jupyter
>     /etc/jupyter
> data:
>     /root/.local/share/jupyter
>     /usr/local/share/jupyter
>     /usr/share/jupyter
> runtime:
>     /root/.local/share/jupyter/runtime

Not sure how to get rid of the /root/ folders. It just keeps coming up even when I run everything without sudo. Any ideas? Thanks

**Comment by CYHSM** [comment]
Seems to work when docker-compose file is adjusted to:

> version: '3.4'
> 
> services:
>   jupyterlab:
>     image: sensorium
>     build:
>       context: .
>     volumes:
>       - .:/project
>       - ./notebooks:/notebooks
>     environment:
>       - JUPYTER_PASSWORD=
>       - JUPYTER_ALLOW_INSECURE_WRITES=true

**Comment by mohammadbashiri** [comment]
@CYHSM thanks for pointing out this issue, and also sharing the solution for it!

Could you tell me what operating system you are using?
