### ISSUE TITLE
Issues faced while running baseline model notebook

### ISSUE THREAD

**Issue by maanavgoyal** [sinzlab/sensorium#109]
1.)Google Colab
While trying to run the notebook on google colab, we got the error `rescale() got an unexpected keyword argument 'channel_axis'` when running `model = stacked_core_full_gauss_readout(dataloaders, random_seed, **model_config).to(device)
model.eval();`

2.)Running the notebook locally
On a Windows system, after following the prerequisite steps, we tried to run the baseline notebook and got the error `Found No Nvidia Driver on your system`. Running the `torch.cuda.is_available()` code on a local file returned `True` but the jupyterlab notebook for sensorium returns `False`. (We updated the nvidia drivers but the issue still remains)
We tried the procedure on a Ubuntu wsl but got the same error

**Comment by KonstantinWilleke** [comment]
Hi! I have a potential solution for your first point. About your second point, I’m not sure, but maybe @cblessing24 can help out.

Could you check your version of scikit image? 
version >=0.19.1 is required. An older one could lead to this issue that you encountered.

**Comment by cblessing24** [comment]
Hi @maanavgoyal. So the GPU is available in WSL2 but not inside the container running on WSL2? If that is the case I would suggest installing [nvidia-container-toolkit](https://docs.nvidia.com/ai-enterprise/deployment-guide/dg-docker.html#enabling-the-docker-repository-and-installing-the-nvidia-container-toolkit) on WSL2. Note that the guide says to install the NVIDIA driver on Linux but in this case I do not think it is necessary. The NVIDIA Driver being installed on Windows should be sufficient.
Unfortunately I do not have a Windows system to test this on but I hoe it will be helpful anyways.

**Comment by maanavgoyal** [comment]
> Hi! I have a potential solution for your first point. About your second point, I’m not sure, but maybe @cblessing24 can help out.
> 
> Could you check your version of scikit image? version >=0.19.1 is required. An older one could lead to this issue that you encountered.

I have scikit version 1.0.2, but the issue still persists
