### ISSUE TITLE
Didn't find the neuro area message...

### ISSUE THREAD

**Issue by SCP-173-cool** [sinzlab/sensorium#111]
I didn't find the area in `area.npy`.
It seems like this:
![image](https://user-images.githubusercontent.com/22118890/187449928-7d704550-71c9-4e6c-9c3d-750dce7cb92a.png)

Maybe I think the `area` means the size of neuro point?

**Comment by KonstantinWilleke** [comment]
Hi!
The `area` refers to the brain area, where the neurons were recorded from. All of our neurons are from visual area V1, so that information there is a bit redundant. Hope that clarifies it!

**Comment by KonstantinWilleke** [comment]
Let me know if you have any more questions. Or if your issue is solved, feel free to close this issue @SCP-173-cool.
