### ISSUE TITLE
Test submission pipeline

### ISSUE THREAD

**Issue by mohammadbashiri** [sinzlab/sensorium#51]
Todo:
- [x] Create a competition
- [x] Add ground truth csv file
- [x] Add zip file for computing metrics
- [x] Make a submission
- [x] Check score

Current issue:
- [x] ~~Cannot upload ground truth (.csv) file~~ @cblessing24 can upload a csv file but cannot create a competition. @cblessing24 would communicate this with the development team

**Comment by mohammadbashiri** [comment]
@cblessing24 @KonstantinWilleke we are done with this issue, right?

**Comment by KonstantinWilleke** [comment]
We are still testing the submission process with the 2 ground truth files + 2 submission files.
