### ISSUE TITLE
Check submission pipeline with trial hash (as a replacement for trial id)

### ISSUE THREAD

**Issue by mohammadbashiri** [sinzlab/sensorium#66]

**Comment by mohammadbashiri** [comment]
@KonstantinWilleke is there a chance we could test the hashed datasets before the datasets becomes publicly available?

**Comment by KonstantinWilleke** [comment]
> @KonstantinWilleke is there a chance we could test the hashed datasets before the datasets become publicly available?

Yes, let's test this, too, tomorrow when we go over everything
