### ISSUE TITLE
SOTA Model

### ISSUE THREAD

**Issue by alexriedel1** [sinzlab/sensorium#76]
Hi!
One of the notebook states the current SOTA model. Is there any paper on how you came up with this model? How does the SOTA compared to other model architectures? 
If I get that right, the model you are referring two is a 4 layer more-or-less basic CNN with some sparsity induced in the convolutional layers. 
Is sparsity also applied to the output?  The concept of readout refers, to how the extracted latent CNN features are mapped to neural responses, is that right? Can you provide any detailed information on this?

**Comment by KonstantinWilleke** [comment]
Hi, thank you for raising these issues!

We'll release a white paper on biorxiv that has further details on the dataset and model architecture (we should have added this to the readme probably).

Our SOTA model is based on this publication from our group: https://openreview.net/forum?id=Tp7kI90Htd

Yes, our core is more or less a basic CNN, but it's using depth-separable convolutions in layers 2-4. The first layer is regularized with a laplace-regularizer, to achieve smooth kernels.
The readout is doing what you have said, mapping the output features of the last core layer to a scalar response per neuron. It finds a single position (in height, width), and extracts the features at this location. Then it's multiplied with the per-neuron readout features (n=64 learned parameters per neuron). How to learn the spatial position is an interesting problem, and in the article above, we propose the "gaussian" readout to solve it.

You can find the definitions of our core and readout in these repositories:
https://github.com/sinzlab/neuralpredictors/blob/0d3d793cc0e1f55ec61c5f9f7a98318b5241a2e9/neuralpredictors/layers/cores/conv2d.py#L27
https://github.com/sinzlab/neuralpredictors/blob/main/neuralpredictors/layers/readouts/gaussian.py

If you are in how the behavior can be included in the model, have a look at this publication too:
https://www.biorxiv.org/content/10.1101/2021.09.03.458870v2

Hope that was helpful, don't hesitate to discuss any issues here! 

Konstantin
